#!/bin/sh
#inkVerbBoss! verb.ink

# This installs Vrk Desktop, Vrk Developer, and Vrk Studio Lite
## This runs: install-vrk-desktop, install-vrk-developer, and install-vrk-studiolite 
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-mi-full
## sudo install-mi-full -r # To re-install without a prompt



# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(/usr/bin/id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-mi-full
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-mi-full
"
exit 22; fi

# Vrk Desktop
/opt/vrk/boss/install-vrk-desktop

# Vrk Developer
/opt/vrk/boss/install-vrk-developer

# Vrk StudioLite
/opt/vrk/boss/install-vrk-studiolite

# Vrk StudioHevy
/opt/vrk/boss/install-vrk-studiohevy

# Remove install progresses
/usr/bin/rm -f /opt/vrk/.vrk-*-installed

# Message
echo "Now you can run set-mi-desktop"
