#!/bin/sh
#inkVerbBoss! verb.ink

# This installs a "lite" version of Ubuntu Studio
## This is automatically run by: install-vrk
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vrk-studiohevy


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-studiohevy
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-studiohevy
"
exit 22; fi

# Check if Vrk StudioLite installed
if [ "${VRK_STUDIOLITE_INSTALLED}" = "YES" ]; then
echo "Vrk StudioLite apps already installed."
exit 0; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-apps
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-apps
"
exit 22; fi


# Include the configs
. /home/${SUDO_USER}/.vrk/configs/lang/stationuser-dirs_CURRENT
. /opt/vrk/machineinfo

# Message
echo "
Installing Vrk StudioHeavy...
"
sleep 1

# Heavy Graphic Design
chkfile=/opt/vrk/.inst-stuhv-1
if [ ! -f "$chkfile" ]; then
echo "
#######
Heavy Graphic Design
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm darktable
/usr/bin/pacman -S --noconfirm blender
/usr/bin/pacman -S --noconfirm scribus
/usr/bin/pacman -S --noconfirm synfigstudio
touch $chkfile; fi

# Heavy Video
chkfile=/opt/vrk/.inst-stuhv-2
if [ ! -f "$chkfile" ]; then
echo "
#######
Heavy Video
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm kdenlive
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm subtitleedit'
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm subtitlecomposer'
touch $chkfile; fi

# Heavy Audio
chkfile=/opt/vrk/.inst-stuhv-3
if [ ! -f "$chkfile" ]; then
echo "
#######
Heavy Audio
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm musescore
/usr/bin/pacman -S --noconfirm gpodder
/usr/bin/pacman -S --noconfirm lmms
/usr/bin/pacman -S --noconfirm ardour
/usr/bin/pacman -S --noconfirm mixxx
/usr/bin/pacman -S --noconfirm muse
touch $chkfile; fi

# Disk Tools
chkfile=/opt/vrk/.inst-stuhv-4
if [ ! -f "$chkfile" ]; then
echo "
#######
DVD Tools
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm brasero
touch $chkfile; fi
brasero

# Wine
chkfile=/opt/vrk/.inst-stuhv-5
if [ ! -f "$chkfile" ]; then
echo "
#######
Wine
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm wine
/usr/bin/pacman -S --noconfirm winetricks
touch $chkfile; fi

# Playonlinux
chkfile=/opt/vrk/.inst-stuhv-6
if [ ! -f "$chkfile" ]; then
echo "
#######
Playonlinux
#######
"
sleep 1
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm playonlinux'
touch $chkfile; fi

# Remove every $chkfile
rm /opt/vrk/.inst-stuhv-*

# Set config
echo "VRK_STUDIOHEVY_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo
touch /home/${SUDO_USER}/.vrk/configs/.studiohevy
## Remove repo temp progress files
rm -f /opt/vrk/.vrk-studiohevy-*

# Cleanup
/usr/bin/pacman -Qdt --noconfirm
/usr/bin/pacman -Scc --noconfirm
/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm'

# Finish
echo "
Vrk Studio Lite is all set.
"
