#!/bin/sh
#inkVerbBoss! verb.ink

# This installs and/or updates Vrk native wallpapers in the Vallpaper module
## This is automatically run by: install-vrk-desktop and install-vrk
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vrk-vallpaper


# Set
## Room name
VALL_ROOM="vrk"
## Root Lockscreen
#ROOT_LOCK_VALL="Vrk-Mesh-Disk.png"

# Set location of Vallpaper install folder
## This can be absolute; or relative ie if via git clone
## Usually, it is the name of the repo and the room is inside like this:
### vrk/vrk
### vrk/avitar-icons
VALL_INST_DIR="/opt/vrk/donjon/vallpaper"

# Set user
VRK_USER=${SUDO_USER}

## Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Make any Vallpaper precondition checks
## Check if Vrk installed for user
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-vallpaper
"
exit 22;  fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-vallpaper
"
exit 22; fi

# Include the config
. /opt/vrk/machineinfo

# Install/Update Vallpaper base
## The actuall Valls exist here under lock and key.
mkdir -p /opt/vall/rooms/${VALL_ROOM}/${VALL_ROOM}
mkdir -p /usr/share/images/vall
## The images are duplicated here for hard system link use.
mkdir -p install-vrk-dirs

# Install/Reset the Vrk Vallpaper Room
## The /usr/share/images folder is used by Xfce and by set-vall and Vallpaper rooms and chrons
rm -rf /opt/vall/rooms/${VALL_ROOM}/
cp -r ${VALL_INST_DIR}/${VALL_ROOM} /opt/vall/rooms/
rm -rf /usr/share/images/vall/${VALL_ROOM}/
ln -sfn /opt/vall/rooms/${VALL_ROOM}/${VALL_ROOM} /usr/share/images/vall/
## Remove any broken symlinks
cd /usr/share/images/vall/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done

# Add Avatar icons (but not Xfce)
if [ -d "/usr/share/pixmaps/faces/" ]; then
ln -sfn /opt/vall/rooms/${VALL_ROOM}/avitar-icons/* /usr/share/pixmaps/faces/
## Remove any broken symlinks
cd /usr/share/pixmaps/faces/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
fi

# Install Vrk vallpapers
## GNOME/global
### If "backgrounds" doesn't exist
mkdir -p /usr/share/backgrounds
mkdir -p /usr/share/gnome-background-properties
rm -rf /usr/share/backgrounds/${VALL_ROOM}/
ln -sfn /opt/vall/rooms/${VALL_ROOM}/${VALL_ROOM} /usr/share/backgrounds/
#### Remove any broken symlinks
cd /usr/share/backgrounds/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
ln -sfn /opt/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/vallpapers-${VALL_ROOM}.xml /usr/share/gnome-background-properties/
#### Remove any broken symlinks
cd /usr/share/gnome-background-properties/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done

## Xfce
if [ "${LINUX_DESKTOP}" = "xfce" ] ; then
    #### DEV NOTE: In Linuxmint Xfce, /usr/share/xfce4/backdrops is a symlink containing native backgrounds for both
    ln -sfn /opt/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/*.png /usr/share/xfce4/backdrops/
    ln -sfn /opt/vall/rooms/${VALL_ROOM}/${VALL_ROOM}/*.jpg /usr/share/xfce4/backdrops/
    ### Remove any broken symlinks
    cd /usr/share/xfce4/backdrops/
    for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
fi

# Vall Config
echo "#!/bin/sh
# inkVerb Vallpaper machine-wide config file, verb.ink

VALL_INST_BY=\"${VRK_USER}\"
VALL_LINUX_DESKTOP=\"${LINUX_DESKTOP}\"
" > /opt/vall/vallmachineinfo

# Finish
echo "
Vrk Vallpaper native wallpapers are installed and up to date.
"

