#!/bin/sh
#inkVerbBoss! verb.ink

# This installs developer tools for Ubuntu
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vrk-developer
## sudo install-vrk-desktop -r # To re-install without a prompt


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check for Vrk Desktop (which installs yay)
. /opt/vrk/machineinfo
if [ ! -e "/opt/vrk/.vrk-desktop-installed" ] || [ -z "$VRK_DESKTOP_INSTALLED" ] || [ "$VRK_DESKTOP_INSTALLED" != "YES" ]; then
echo "must run install-vrk-desktop first"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-developer
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-developer
"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-developer
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-developer
"
exit 22; fi

# Check for Internet connection
/usr/bin/ping -c 1 -q google.com > /dev/null 2>&1
if [ "$?" != "0" ]; then
echo "No Internet connection. Connect, then try again."; exit 0; fi

# Include the progress config
. /home/${SUDO_USER}/.vrk/configs/lang/stationuser-dirs_CURRENT

# Update
/usr/bin/pacman -Sy archlinux-keyring --noconfirm
/usr/bin/pacman -Syy --noconfirm
/usr/bin/pacman -Scc --noconfirm
/usr/bin/su worker -c '/usr/bin/yay -Syy --noconfirm'
/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm'
/usr/bin/su worker -c '/usr/bin/yay -Yc --noconfirm'

# Message
echo "
Installing Vrk Developer...
"
sleep 1

# Postman
chkfile=/opt/vrk/.inst-dev-1
if [ ! -f "$chkfile" ]; then
echo "
#######
Postman
#######
"
sleep 1
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm postman-bin'
touch $chkfile; fi

# GitLab
chkfile=/opt/vrk/.inst-dev-2
if [ ! -f "$chkfile" ]; then
echo "
#######
Skipping GitLab, you can do that yourself
#######
"
sleep 1
#/usr/bin/pacman -S --noconfirm --needed gitlab
touch $chkfile; fi

# BlackArch Repos
chkfile=/opt/vrk/.inst-dev-3
if [ ! -f "$chkfile" ]; then
echo "
#######
BlackArch Repos
#######
"
sleep 1
curl -O https://blackarch.org/strap.sh
echo 5ea40d49ecd14c2e024deecf90605426db97ea0c strap.sh | sha1sum -c
/usr/bin/chmod +x strap.sh
/usr/bin/./strap.sh
/usr/bin/pacman -Syu
/usr/bin/rm -f ./strap.sh
touch $chkfile; fi

# # Slack, Obsidian & Gitter
# chkfile=/opt/vrk/.inst-dev-4
# if [ ! -f "$chkfile" ]; then
# echo "
# #######
# Slack, Obsidian & Gitter
# #######
# "
# sleep 1
# /usr/bin/pacman -S --noconfirm --needed obsidian
# /usr/bin/su worker -c '/usr/bin/yay -S --noconfirm slack-desktop'
# /usr/bin/su worker -c '/usr/bin/yay -S --noconfirm gitter-bin'
# touch $chkfile; fi

# # Figma
# chkfile=/opt/vrk/.inst-dev-5
# if [ ! -f "$chkfile" ]; then
# echo "
# #######
# Figma
# #######
# "
# sleep 1
# /usr/bin/su worker -c '/usr/bin/yay -S --noconfirm figma-linux-bin'
# touch $chkfile; fi

# # Swagger
# chkfile=/opt/vrk/.inst-dev-6
# if [ ! -f "$chkfile" ]; then
# echo "
# #######
# Swagger
# #######
# "
# sleep 1
# /usr/bin/su worker -c '/usr/bin/yay -S --noconfirm swagger-ui'
# touch $chkfile; fi

# # Draw.io
# chkfile=/opt/vrk/.inst-dev-7
# if [ ! -f "$chkfile" ]; then
# echo "
# #######
# Draw.io
# #######
# "
# sleep 1
# /usr/bin/su worker -c '/usr/bin/yay -S --noconfirm drawio-desktop-bin'
# touch $chkfile; fi

# Remove every $chkfile
rm /opt/vrk/.inst-dev-*

# Set config
if [ "${VRK_DEVELOPER_INSTALLED}" != "YES" ]; then
sed -i "s/VRK_DEVELOPER_INSTALLED=.*/VRK_DEVELOPER_INSTALLED=\"YES\"/" /opt/vrk/machineinfo; fi
if [ -z "${VRK_DEVELOPER_INSTALLED}" ]; then
echo "VRK_DEVELOPER_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo; fi
touch /home/${SUDO_USER}/.vrk/configs/.Developer
## Remove repo temp progress files
rm -f /opt/vrk/.vrk-developer-*

# Cleanup
/usr/bin/pacman -Rsc --noconfirm
/usr/bin/pacman -Scc --noconfirm
/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm'
/usr/bin/su worker -c '/usr/bin/yay -Yc --noconfirm'

# Finish
echo "
Vrk Developer is all set.
"
