#!/bin/sh
#inkVerbBoss! verb.ink

# This installs a "lite" version of Ubuntu Studio
## This is automatically run by: install-vrk
## Prerequesite: Vrk™ must be installed

# How to use:
## sudo install-vrk-studiohevy
## sudo install-vrk-desktop -r # To re-install without a prompt


# Set user
VRK_USER=${SUDO_USER}

# Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Check if installed
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check for Vrk Desktop (which installs yay)
. /opt/vrk/machineinfo
if [ ! -e "/opt/vrk/.vrk-desktop-installed" ] || [ -z "$VRK_DESKTOP_INSTALLED" ] || [ "$VRK_DESKTOP_INSTALLED" != "YES" ]; then
echo "must run install-vrk-desktop first"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-studiohevy
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-studiohevy
"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo install-vrk-apps
"
exit 22; fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo install-vrk-apps
"
exit 22; fi

# Check for Internet connection
/usr/bin/ping -c 1 -q google.com > /dev/null 2>&1
if [ "$?" != "0" ]; then
echo "No Internet connection. Connect, then try again."; exit 0; fi

# Include the configs
. /home/${SUDO_USER}/.vrk/configs/lang/stationuser-dirs_CURRENT

# Update
/usr/bin/pacman -Sy archlinux-keyring --noconfirm
/usr/bin/pacman -Syy --noconfirm
/usr/bin/pacman -Scc --noconfirm
/usr/bin/su worker -c '/usr/bin/yay -Syy --noconfirm'
/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm'

# Message
echo "
Installing Vrk StudioHeavy...
"
sleep 1

# Heavy Graphic Design
chkfile=/opt/vrk/.inst-stuhv-1
if [ ! -f "$chkfile" ]; then
echo "
#######
Heavy Graphic Design
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm --needed darktable
/usr/bin/pacman -S --noconfirm --needed blender
/usr/bin/pacman -S --noconfirm --needed scribus
/usr/bin/pacman -S --noconfirm --needed synfigstudio
touch $chkfile; fi

# Heavy Video
chkfile=/opt/vrk/.inst-stuhv-2
if [ ! -f "$chkfile" ]; then
echo "
#######
Heavy Video
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm --needed kdenlive
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm --needed subtitleedit'
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm --needed subtitlecomposer'
touch $chkfile; fi

# Heavy Audio
chkfile=/opt/vrk/.inst-stuhv-3
if [ ! -f "$chkfile" ]; then
echo "
#######
Heavy Audio
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm --needed musescore
/usr/bin/pacman -S --noconfirm --needed gpodder
/usr/bin/pacman -S --noconfirm --needed lmms
/usr/bin/pacman -S --noconfirm --needed ardour
/usr/bin/pacman -S --noconfirm --needed mixxx
/usr/bin/pacman -S --noconfirm --needed muse
touch $chkfile; fi

# Disk Tools
chkfile=/opt/vrk/.inst-stuhv-4
if [ ! -f "$chkfile" ]; then
echo "
#######
DVD Tools
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm --needed brasero
touch $chkfile; fi
brasero

# Wine
chkfile=/opt/vrk/.inst-stuhv-5
if [ ! -f "$chkfile" ]; then
echo "
#######
Wine
#######
"
sleep 1
/usr/bin/pacman -S --noconfirm --needed wine
/usr/bin/pacman -S --noconfirm --needed winetricks
touch $chkfile; fi

# Playonlinux
chkfile=/opt/vrk/.inst-stuhv-6
if [ ! -f "$chkfile" ]; then
echo "
#######
Playonlinux
#######
"
sleep 1
/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm --needed playonlinux'
touch $chkfile; fi

# Remove every $chkfile
rm /opt/vrk/.inst-stuhv-*

# Set config
if [ "${VRK_STUDIOHEVY_INSTALLED}" != "YES" ]; then
sed -i "s/VRK_STUDIOHEVY_INSTALLED=.*/VRK_STUDIOHEVY_INSTALLED=\"YES\"/" /opt/vrk/machineinfo; fi
if [ -z "${VRK_STUDIOHEVY_INSTALLED}" ]; then
echo "VRK_STUDIOHEVY_INSTALLED=\"YES\"" >> /opt/vrk/machineinfo; fi
touch /home/${SUDO_USER}/.vrk/configs/.studiohevy
## Remove repo temp progress files
rm -f /opt/vrk/.vrk-studiohevy-*

# Cleanup
/usr/bin/pacman -Qdt --noconfirm
/usr/bin/pacman -Scc --noconfirm
/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm'

# Finish
echo "
Vrk Studio Lite is all set.
"
