#!/bin/sh
#inkVerbBoss! verb.ink

# This uninstalls the Vrk vallpaper framework
## This also removes Vrk icons (because this is intended as part of removing all of Vrk)

# How to use:
## sudo uninstall-vrk-vallpaper


# Set
## Room name
VALL_ROOM="vrk"
## Root Lockscreen
#ROOT_LOCK_VALL="Vrk-Mesh-Disk.png"

# Set location of Vallpaper install folder
## This can be absolute; or relative ie if via git clone
## Usually, it is the name of the repo and the room is inside like this:
### vrk/vrk
### vrk/avitar-icons
VALL_INST_DIR="/opt/vrk/donjon/vallpaper"

# Set user
VRK_USER=${SUDO_USER}

## Check if Vrk installed on this machine
if [ ! -f /opt/vrk/machineinfo ]; then
echo "Install Vrk on this machine first. See README.md"
exit 22; fi

# Make any Vallpaper precondition checks
## Check if Vrk installed for user
if [ ! -f /home/${VRK_USER}/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22; fi

# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
like this:
sudo uninstall-vrk-vallpaper
"
exit 22;  fi; fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo uninstall-vrk-vallpaper
"
exit 22; fi

# Remove Vallpaper base
## The actuall Valls exist here under lock and key.
rm -rf /opt/vall
## The images are duplicated here for hard system link use.
rm -rf /usr/share/images/vall

# Remove any broken symlinks
cd /usr/share/pixmaps/faces/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
cd /usr/share/backgrounds/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
cd /usr/share/gnome-background-properties/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done
cd /usr/share/xfce4/backdrops/
for x in * .[!.]* ..?*; do if [ -L "$x" ] && ! [ -e "$x" ]; then rm -- "$x"; fi; done

# Icons
rm -f /usr/share/pixmaps/faces/inkVerb-*.png

# Finish
echo "
Vrk Vallpaper uninstalled.
"

