#!/bin/sh
#inkVerbSurfer! verb.ink

# This refreshes the Vrk tools (boss, surf, donjon, malibu) in .vrk for where they actuall reside in /opt/vrk

# How to use:
## sudo vrkfresh


# Update per user
getent passwd | while IFS=: read -r name password uid gid gecos home shell; do
  # only users that own their home directory
  if [ -d "$home" ] && [ "$(stat -c %u "$home")" = "$uid" ]; then
    # only users that have a shell, and a shell is not equal to /bin/false or /usr/sbin/nologin
    if [ ! -z "$shell" ] && [ "$shell" != "/bin/false" ] && [ "$shell" != "/usr/sbin/nologin" ]; then
      if [ -d "/home/$name/.vrk" ]; then

        # Assign our vrk variable
        vrk_USER="$name"

        # Refresh go VPNs
        for vrk_malibu_PATH in /home/${vrk_USER}/.vrk/malibu/vpn.*; do
          vrk_malibu=$(echo ${vrk_malibu_PATH} | sed "s:/home/${vrk_USER}/.vrk/malibu/::")
          if grep -Fq "#inkVerbGosurfer" ${vrk_malibu_PATH}; then
            mkdir -p /opt/vrk/malibu/${vrk_USER}
            cp ${vrk_malibu_PATH} /opt/vrk/malibu/${vrk_USER}/
            chmod 755 /opt/vrk/malibu/${vrk_USER}/${vrk_malibu}
          fi
        done

        # Update droids
        chmod 755 /opt/vrk/droids/${vrk_USER}/*

        # Check if installed
        if [ ! -f /home/${vrk_USER}/.vrk/configs/stationinfo ]; then
        echo "Install Vrk first. See README.md"
        exit 22
        fi

        # Check to make sure this is run as sudo, but not run by root
        ## If root or sudo
        if [ "$(id -u)" = "0" ]; then
        ## If sudo is NOT present
         if [ -z "${SUDO_COMMAND}" ]; then
        echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
        like this:
        sudo vrkfresh
        "
        exit 22
         fi
        fi
        ## If sudo is NOT present
        if [ -z "${SUDO_COMMAND}" ]; then
        echo "Run this as a sudoer sudo, not merely as a sudoer.
        like this:
        sudo vrkfresh
        "
        exit 22
        fi

        # Include the config
        . /home/${vrk_USER}/.vrk/configs/stationinfo

        # Refresh the user directory
        ## For any user
        mkdir -p /home/${vrk_USER}/.vrk/boards
        rm -rf  /home/${vrk_USER}/.vrk/boards/*
        cp -rf /opt/vrk/droids/ALL/* /home/${vrk_USER}/.vrk/boards/
        cp -rf /opt/vrk/droids/${vrk_USER}/* /home/${vrk_USER}/.vrk/boards/
        cp /opt/vrk/surf/* /home/${vrk_USER}/.vrk/boards/
        rm -rf /home/${vrk_USER}/.vrk/donjon
        cp -rf /opt/vrk/donjon /home/${vrk_USER}/.vrk/
        chmod 755 /opt/vrk/boss/*
        chmod 755 /opt/vrk/surf/*
        chmod 755 /opt/vrk/donjon/*
        chmod 754 /opt/vrk/donjon/vrktemplates/7_BASH
        chmod 755 /opt/vrk/droids/ALL/*
        mkdir -p /home/${vrk_USER}/.vrk/go
        ## For a sudoer
        if [ "${USER_BOSSYN}" = "CAN_BOSS" ]; then
        rm -rf  /home/${vrk_USER}/.vrk/boss
        ln -sfn /opt/vrk/boss/* /home/${vrk_USER}/.vrk/boards/
        fi
        ## Own
        chown -R ${vrk_USER}:${vrk_USER} /home/${vrk_USER}/.vrk

        # Finish per user
        echo "Vrk tools are up-to-date for ${vrk_USER}."

# End the loop
      fi
    fi
  fi
done

# Finish all
echo "Vrk tools up-to-date for all vrkers."
