#!/bin/sh
#inkVerbSurfer! verb.ink

# This refreshes the Vrk tools (boss, surf, donjon, malibu) in .vrk for where they actuall reside in /opt/vrk

# How to use:
## sudo vrkfresh


# Update per user
getent passwd | while IFS=: read -r name password uid gid gecos home shell; do
  # only users that own their home directory
  if [ -d "$home" ] && [ "$(stat -c %u "$home")" = "$uid" ]; then
    # only users that have a shell, and a shell is not equal to /bin/false or /usr/sbin/nologin
    if [ ! -z "$shell" ] && [ "$shell" != "/bin/false" ] && [ "$shell" != "/usr/sbin/nologin" ]; then
      if [ -d "/home/$name/.vrk" ]; then

        # Assign our vrk variable
        vrk_USER="$name"

        # Refresh go VPNs
        if ls /home/${vrk_USER}/.vrk/malibu/vpn.* > /dev/null 2>&1; then
          for vrk_malibu_PATH in /home/${vrk_USER}/.vrk/malibu/vpn.*; do
            vrk_malibu=$(echo ${vrk_malibu_PATH} | sed "s:/home/${vrk_USER}/.vrk/malibu/::")
            if grep -Fq "#inkVerbGosurfer" ${vrk_malibu_PATH}; then
              mkdir -p /opt/vrk/malibu/${vrk_USER}
              cp ${vrk_malibu_PATH} /opt/vrk/malibu/${vrk_USER}/
              chmod 755 /opt/vrk/malibu/${vrk_USER}/${vrk_malibu}
            fi
          done
        fi

        # Update droids
        if [ -d "/opt/vrk/droids/${vrk_USER}" ]; then
          chmod 755 /opt/vrk/droids/${vrk_USER}/*
        fi

        # Check if installed
        if [ ! -f /home/${vrk_USER}/.vrk/configs/stationinfo ]; then
        echo "Install Vrk first. See README.md"
        exit 22
        fi

        # Check to make sure this is run as sudo, but not run by root
        ## If root or sudo
        if [ "$(id -u)" = "0" ]; then
        ## If sudo is NOT present
         if [ -z "${SUDO_COMMAND}" ]; then
        echo "Run this as a sudoer sudo, not as root. You'll have to exit root and perhaps re-login as the sudoer. Then...
        like this:
        sudo vrkfresh
        "
        exit 22
         fi
        fi
        ## If sudo is NOT present
        if [ -z "${SUDO_COMMAND}" ]; then
        echo "Run this as a sudoer sudo, not merely as a sudoer.
        like this:
        sudo vrkfresh
        "
        exit 22
        fi

        # Include the config
        . /home/${vrk_USER}/.vrk/configs/stationinfo

        # Refresh the user directory
        ## For any user
        mkdir -p /home/${vrk_USER}/.vrk/boards
        rm -rf  /home/${vrk_USER}/.vrk/boards/*
        if [ -d "/home/${vrk_USER}/.vrk/boards/" ] && [ -d "/opt/vrk/droids/ALL/" ]; then
          cp -rf /opt/vrk/droids/ALL/* /home/${vrk_USER}/.vrk/boards/
        fi
        if [ -d "/opt/vrk/droids/${vrk_USER}/" ] && [ -d "/home/${vrk_USER}/.vrk/boards/" ]; then
          cp -rf /opt/vrk/droids/${vrk_USER}/* /home/${vrk_USER}/.vrk/boards/
        fi
        if [ -d "/opt/vrk/surf/" ] && [ -d "/home/${vrk_USER}/.vrk/boards/" ]; then
          cp /opt/vrk/surf/* /home/${vrk_USER}/.vrk/boards/
        fi
        rm -rf /home/${vrk_USER}/.vrk/donjon
        if [ -d "/opt/vrk/donjon" ] && [ -d "/home/${vrk_USER}/.vrk/" ]; then
          cp -rf /opt/vrk/donjon /home/${vrk_USER}/.vrk/
        fi
        if [ -d "/opt/vrk/boss" ]; then
          chmod 755 /opt/vrk/boss/*
        fi
        if [ -d "/opt/vrk/surf" ]; then
          chmod 755 /opt/vrk/surf/*
        fi
        if [ -d "/opt/vrk/donjon" ]; then
          chmod 755 /opt/vrk/donjon/*
        fi
        if [ -e "/opt/vrk/donjon/vrktemplates/7_BASH" ]; then
          chmod 754 /opt/vrk/donjon/vrktemplates/7_BASH
        fi
        if [ -d "/opt/vrk/droids/ALL" ]; then
          chmod 755 /opt/vrk/droids/ALL/*
        fi
        if [ -d "/home/${vrk_USER}/.vrk/" ]; then
          mkdir -p /home/${vrk_USER}/.vrk/malibu
        fi
        ## For a sudoer
        if [ "${USER_BOSSYN}" = "CAN_BOSS" ]; then
          rm -rf  /home/${vrk_USER}/.vrk/boss
        fi
        if [ -d "/opt/vrk/boss" ] && [ -d "/home/${vrk_USER}/.vrk/boards/" ]; then
          ln -sfn /opt/vrk/boss/* /home/${vrk_USER}/.vrk/boards/
        fi
        ## Own

        # Finish per user
        echo "Vrk tools are up-to-date for ${vrk_USER}."

# End the loop
      fi
    fi
  fi
done

# Finish all
echo "Vrk tools up-to-date for all vrkers."
