#!/bin/sh
#inkVerbSurfer! verb.ink

# This creates a new .malibu surver config and adds it to .ssh/config and FileZilla

# How to use:
## ssh-new-all [surfer name] [remote user] [remote IP] [ssh_key name] [port - optional]


surfername="$1"
User="$2"
Keyname="$4"

# Check if installed
if [ ! -f ~/.vrk/configs/stationinfo ]; then
echo "Install Vrk first. See README.md"
exit 22
fi

# Check for key
if [ ! -f ~/.ssh/${Keyname} ]; then
/opt/vrk/surf/ssh-craft-key ${Keyname}
echo "Since it did not exist, ssh key ${Keyname} has been created.
The contents of ${Keyname}.pub should be added to .ssh/authorized_keys for remote server's user '${User}' before it can be used.
Use: ssh-upload-key ${surfername} ${Keyname} [server-password]"
fi

# Run them each
/opt/vrk/surf/ssh-new-surfer $@
/opt/vrk/surf/ssh-add-ssh ${surfername}
/opt/vrk/surf/ssh-add-filezilla ${surfername}

