#!/bin/sh
#inkVerbSurfer! verb.ink

# This shows information and status of the current Vrk version and user

# How to use:
## vinf

# Include configs
. ~/.vrk/configs/stationinfo
. /opt/vrk/machineinfo

# Tell all
echo "
Vrk Repo:           $VRKUPDATEREPO
Archtctr:           $ARCHITECTURE
Distro:             $LINUX_DESKTOP

Deskop Basics:      $VRK_DESKTOP_INSTALLED
Studio Lite:        $VRK_STUDIOLITE_INSTALLED
Studio Hevy:        $VRK_STUDIOHEVY_INSTALLED
Developer Tools:    $VRK_DEVELOPER_INSTALLED
Desktop Set:        $VRK_DESKTOP_SET

User Boss?:         $USER_BOSSYN
Cloud:              $VRK_CLOUD_DIR
Work:               $VRK_WORK_DIR
Vrk Verno:          $USER_KVERNO"

